name: CI for AuthSphere

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 # Use the Python version of your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed for running tests
          pip install python-dotenv  # Install python-dotenv if needed

      - name: Set environment variables from secrets

        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}
          REFRESH_TOKEN_EXPIRE: ${{ secrets.REFRESH_TOKEN_EXPIRE }}
        run: |
          echo "SECRET_KEY=$SECRET_KEY"
          echo "ALGORITHM=$ALGORITHM"
          echo "ACCESS_TOKEN_EXPIRE=$ACCESS_TOKEN_EXPIRE"
          echo "REFRESH_TOKEN_EXPIRE=$REFRESH_TOKEN_EXPIRE"
          echo "Environment variables set"
          pytest tests/

      # Run tests
      - name: Run tests
        run: pytest tests/
